title: Typologically
description: A website about Typo Art and logic
footer_text: Copyright 2021 Jill Ã‡akmak
header_feature_image: ../uploads/clark-tibbs-oqstl2l5oxi-unsplash.jpg
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
